#!/bin/sh 
# 
# script to bring up the tun device in QEMU in bridged mode 
# first parameter is name of tap device (e.g. tap0)
#
# some constants specific to the local host - change to suit your host
#
ETH0IPADDR=192.168.131.130
MASK=255.255.255.0
GATEWAY=192.168.131.130
BROADCAST=192.168.0.255
#
# First take eth0 down, then bring it up with IP address 0.0.0.0 
#
/sbin/ifdown ens33
/sbin/ifconfig ens33 0.0.0.0 promisc up
#
# Bring up the tap device (name specified as first argument, by QEMU)
#
echo "good so far?"
echo $1 
#/usr/sbin/openvpn --mktun --dev $1 --user `id -un`
/sbin/ifconfig $1 0.0.0.0 promisc up
#
# create the bridge between eth0 and the tap device
#

if /usr/sbin/brctl addbr br0; then
echo "Worked"
else
echo "Didn't Work"
fi

/usr/sbin/brctl addbr br0
/usr/sbin/brctl addif br0 ens33
/usr/sbin/brctl addif br0 $1

if /usr/sbin/brctl addbr br0; then
echo "Worked"
else
echo "Didn't Work"
fi

# 
# only a single bridge so loops are not possible, turn off spanning tree protocol
#
/usr/sbin/brctl stp br0 off 
# 
# Bring up the bridge with ETH0IPADDR and add the default route 
#
/sbin/ifconfig br0 $ETH0IPADDR netmask $MASK broadcast $BROADCAST
echo "did this happen yet?"
#/sbin/route del -net 192.168.131.0/24
echo "did this happen yet?"
/sbin/route add default gw $GATEWAY
#
# stop firewall - comment this out if you don't use Firestarter
#
#/sbin/service firestarter stop
