#!/bin/sh 
# 
# Script to bring down and delete bridge br0 when QEMU exits 
# 
# Bring down eth0 and br0 
#
/sbin/ifdown ens33
/sbin/ifdown br0
/sbin/ifconfig br0 down 
# 
# Delete the bridge
#
/usr/sbin/brctl delbr br0 
# 
# bring up eth0 in "normal" mode 
#
/sbin/ifconfig ens33 -promisc
/sbin/ifup ens33 
route del default
route add default gw 192.168.131.134
#
# delete the tap device
#
#/usr/sbin/openvpn --rmtun --dev $1
#
# start firewall again
# 
#/sbin/service firestarter start 
